#!/bin/csh 
# 
# Create CSS3.0 .origin ertion table from ascii cmt_event file
# Usage: creat_origin cmt_event db_name
#
set time=`awk '{if(NR == 1){yd=$2-1970;vis=int((yd+1)/4); s=(365*yd+vis+$3-1)*86400.0+($4*60+$5)*60+$6; printf("%17.5f", s);}}' < $1`
awk 'BEGIN{t='$time';}{if(NR == 1) \
printf("%9.4f %9.4f %9.4f %17.5f %8d %8d %8d %4d %4d %4d %8d %8d %-7.7s %9.4f %-1.1s %7.2f %8d %7.2f %8d %7.2f %8d %-15.15s %-15.14s %8d %-17.17s\n", \
$7,$8,$9,t,1,-1,$2*1000+$3,-1,-1,-1,-1,-1,"-",-999.0000,"-",-999.0,-1,-999.0,-1, \
-999.00,-1,"-","PDE & Hvd CMT",-1,-1); \
}' $1 > $2.origin
exit
